Feature/implement income information service
hl-management/orca-api pull request #13
Opened 2023-11-02 05:40 UTC by KhoaNDAHopee

2023-11-13 08:38 UTC, mizumotok requested changes

2023-11-13 08:38 UTC, mizumotok commented on lib/orca_api/information_service.rb
> +  class InformationService < Service
単なる**Information**ではないので、`IncomeInformationService`にしましょう。

2023-11-13 08:38 UTC, mizumotok commented on lib/orca_api/information_service.rb
> +    def list(base_date = "", patient_id = "", type = "date")
base_dateというのがわかりにくいです。
dateとmonthとyearの複数指定も可能です。
```ruby
def list(patient_id = "", date = nil, month = nil, year = nil)
```
orca APIとあわせてこのようにしたいです。

2023-11-13 10:58 UTC, KhoaNDAHopee commented on lib/orca_api/information_service.rb
> +    def list(base_date = "", patient_id = "", type = "date")
コメントを対応しました
もう一度ご確認をよろしくお願い致します

2023-11-13 11:02 UTC, mizumotok requested changes

2023-11-13 11:02 UTC, mizumotok commented on lib/orca_api/income_information_service.rb
> +      if date.present?
>  ※１：　診療日、診療月、診療年のいずれかを指定。複数指定があった場合は診療日、診療月、診療年の順で指定があったものとみなします。

こう書いてありますので、複数指定は可能です。
場合分けしないで、入れていいと思います。

2023-11-14 02:46 UTC, KhoaNDAHopee commented on lib/orca_api/income_information_service.rb
> +      if date.present?
コメントを対応しました
もう一度ご確認をよろしくお願い致します

2023-11-16 09:23 UTC, mizumotok requested changes

2023-11-16 09:23 UTC, mizumotok commented on lib/orca_api/income_information_service.rb
> +          "Perform_Year" => year,
仕様ではPerform_Date、Perform_Month、Perform_Yearは必須ではありません。
空文字を入れるのではなく、リクエストに含めないようにしましょう。

---
番号 | 項目名 | 内容 | 例 | 備考
-- | -- | -- | -- | --
1 | Patient_ID | 患者番号 | 12 | 必須
2 | Perform_Date | 診療日 | 2013-10-10 | 省略時はシステム日付※１
3 | Perform_Month | 診療月 | 2013-10 | ※１
4 | Perform_Year | 診療年 | 2013 | ※１

<p style="margin: 0px 0px 15px 10px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Hiragino Kaku Gothic ProN&quot;; font-size: 13.44px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> ※１：　診療日、診療月、診療年のいずれかを指定。複数指定があった場合は診療日、診療月、診療年の順で指定があったものとみなします。<br style="margin: 0px; padding: 0px;">　　　　いずれも未指定の場合は診療日（システム日付）が設定されます。</p><br class="Apple-interchange-newline">

2023-11-17 06:42 UTC, KhoaNDAHopee commented on lib/orca_api/income_information_service.rb
> +          "Perform_Year" => year,
コメントを対応しました
もう一度ご確認をよろしくお願い致します

2023-11-17 06:46 UTC, mizumotok approved these changes

2023-11-17 06:46 UTC, merged