HLM001-1500 【医療事務】給管帳との連携_患者の新規登録
hl-management/orca-api pull request #17
Opened 2024-01-23 08:04 UTC by KhoaNDAHopee

BackLog: https://hlm.backlog.com/view/HLM001-1500
![image](https://github.com/hl-management/orca-api/assets/104702649/a2140639-f094-4348-b11d-37b83ec008af)

対応内容：
homisに患者登録をすると、給管帳を利用するクリニックの場合は、給管帳に患者を作成する

2024-02-01 11:23 UTC, mizumotok requested changes

2024-02-01 11:23 UTC, mizumotok commented on lib/orca_api/orca_qkan_service/patient_qkan_service.rb
> +    class PatientQkanService < Service
他のクラスにあわせて、`QkanPatientService`にしましょう。

2024-02-05 01:19 UTC, KhoaNDAHopee commented on lib/orca_api/orca_qkan_service/patient_qkan_service.rb
> +    class PatientQkanService < Service
コメントを対応しました
もう一度ご確認をよろしくお願い致します

2024-02-06 05:47 UTC, mizumotok approved these changes

2024-02-06 05:47 UTC, merged