HLM001-1504 【医療事務】給管帳との連携_サービスコードの取得
hl-management/orca-api pull request #18
Opened 2024-02-15 07:10 UTC by KhoaNDAHopee

PBI: https://hlm.backlog.com/view/HLM001-1504

2024-02-22 02:13 UTC, mizumotok requested changes

2024-02-22 02:13 UTC, mizumotok commented on lib/orca_api/orca_qkan_service/qkan_homecare_master_service.rb
> +      def get(target_date = "")
もう少し汎用的につくってもらってもいいですか。
個別設定はhomis側でやってください。
```ruby
# @param target_date [String] 対象年月日
# @param service_code_kind [String] 介護サービス種類コード
# @param santei_item_information [Array<Hash>] 算定項目情報
# @option santei_item_information :item_no 算定項目番号
# @option santei_item_information :search_value 算定項目検索値
def get(target_date: '', service_code_kind:, santei_item_information: [])

2024-02-22 02:13 UTC, mizumotok commented on lib/orca_api/orca_qkan_service.rb
> +      QkanHomecareMasterService
給官鳥のマスタ管理サービスは３つあります。
- mservicelst
- mservice_codelst
- mservice_codeparam

今回はmservice_codelstですが、今後のために給官鳥APIと対比できる名前にしてください。

QkanHomecareMasterService -> `QkanMasterCodeListService`

2024-02-22 09:39 UTC, KhoaNDAHopee commented on lib/orca_api/orca_qkan_service/qkan_homecare_master_service.rb
> +      def get(target_date = "")
こちらを修正しました。

2024-02-22 09:39 UTC, KhoaNDAHopee commented on lib/orca_api/orca_qkan_service.rb
> +      QkanHomecareMasterService
こちらを修正しました。

2024-02-26 02:04 UTC, mizumotok requested changes

2024-02-26 02:04 UTC, mizumotok commented on lib/orca_api/orca_qkan_service/qkan_master_code_list_service.rb
> +        santei_items_xml = params[:santei_item_information].map do |item|
`:santei_item_information`は必須ではないのでない場合があります。

2024-02-26 03:34 UTC, KhoaNDAHopee commented on lib/orca_api/orca_qkan_service/qkan_master_code_list_service.rb
> +        santei_items_xml = params[:santei_item_information].map do |item|
コメントを対応しました
もう一度ご確認をよろしくお願い致します

2024-02-26 07:25 UTC, mizumotok approved these changes

2024-02-26 07:25 UTC, merged