Feature/insurance list
hl-management/orca-api pull request #4
Opened 2023-01-29 01:58 UTC by epona-ruijie-hao

2023-02-06 23:50 UTC, NaitoYuki reviewed
LGMT!

2023-02-06 23:50 UTC, NaitoYuki approved these changes

2023-02-07 08:55 UTC, mizumotok approved these changes

2023-02-07 10:06 UTC, mizumotok requested changes

2023-02-07 10:06 UTC, mizumotok commented on lib/orca_api/insurance_service.rb
> +    def insurance_list(patient_id)
insurance_serviceはマスターデータとなる保険・公費一覧を取得しているので、ここに患者のデータを入れるのはそぐわないです。

このプロジェクトの構成としては `lib/orca_api/patient_service/`に新しいサービスを作るのがふさわしいかと思います。

```ruby
module OrcaApi
  class PatientService < Service
    class AllHealthInsurances
      def get(id)
```
lib/orca_api/patient_service/all_health_insurances.rb

2023-02-07 10:27 UTC, mizumotok commented on lib/orca_api/insurance_service.rb
> +    def insurance_list(patient_id)
https://github.com/hl-management/orca-api/blob/4cfcca1031f4356d0bc8601e41f4570f65704f62/lib/orca_api/patient_service.rb#L333
ここに`AllHealthInsurances`を追加

2023-02-07 11:42 UTC, epona-ruijie-hao commented on lib/orca_api/insurance_service.rb
> +    def insurance_list(patient_id)
@mizumotok  修正しました

2023-02-07 11:44 UTC, mizumotok approved these changes

2023-02-07 11:44 UTC, merged