add patient search feature
hl-management/orca-api pull request #7
Opened 2023-03-25 23:31 UTC by epona-ruijie-hao

2023-03-29 00:33 UTC, NaitoYuki approved these changes

2023-03-30 11:15 UTC, mizumotok requested changes

2023-03-30 11:15 UTC, mizumotok commented on lib/orca_api/patient_search_service.rb
> +  class PatientSearchService < Service
患者関連はPatientServiceの下に置きましょう。
```ruby
module OrcaApi
  class PatientService < Service
    class PatientSearchService < Service
```

PatientModServiceもそうしたい。。。

2023-03-30 23:59 UTC, epona-ruijie-hao commented on lib/orca_api/patient_search_service.rb
> +  class PatientSearchService < Service
@mizumotok 

```
module OrcaApi
 class PatientService < Service
    class SearchService < Service
```

と　

```
module OrcaApi
 class PatientService < Service
    class PatientSearchService < Service
```
どちがいい？

2023-03-31 04:00 UTC, mizumotok commented on lib/orca_api/patient_search_service.rb
> +  class PatientSearchService < Service
@epona-ruijie-hao 
ああ、難しいですね。
`SearchService`にしたいところですが、何のSearchか分かりにくくなりそうなので、`PatientSearchService`にしましょう。

2023-04-04 02:53 UTC, mizumotok approved these changes

2023-04-04 02:54 UTC, merged